name = "gta-lorcana-safe-to-id"
main = "index.js"
compatibility_date = "2025-09-27"

[observability]
[observability.logs]
enabled = true
invocation_logs = true

[env.production]
routes = [
  { pattern = "api.gtalorcana.ca/safe-to-id/*", zone_name = "gtalorcana.ca" },
]